//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departement()
        {
            this.Biddings = new HashSet<Bidding>();
        }
    
        public int DepartementID { get; set; }
        public string DepartementName { get; set; }
        public Nullable<int> InstanceID { get; set; }
        public string KeyContactName { get; set; }
        public string KeyContactEmail { get; set; }
        public string KeyContactPhone { get; set; }
        public Nullable<int> NumberOfStudent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bidding> Biddings { get; set; }
        public virtual Instance Instance { get; set; }
    }
}
