//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainCRM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class niitcarev2Entities : DbContext
    {
        public niitcarev2Entities()
            : base("name=niitcarev2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bidding> Biddings { get; set; }
        public virtual DbSet<Departement> Departements { get; set; }
        public virtual DbSet<Instance> Instances { get; set; }
        public virtual DbSet<Modul> Moduls { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
    }
}
